### PR TITLE
Pull Neat and Bourbon from NPM instead of Bower

### PR DESCRIPTION
**Pull request by jrjohnson**
I set out to have neat installed via NPM instead of bower, but I was unable to do so without updating ember-cli. So this PR got a little bit large.  If you want I can split it up into 2 pieces (1 to update ember, and 1 to remove node), just let me know.

I took the approach for loading from npm from the ember-cli-bourbon project and I also took the liberty of mostly copying their single acceptance test.

### CODE REVIEW

**Comment by tzellman** [comment]
Interesting timing! I was just about to do the same thing. :tada:

**Review by tzellman — APPROVED** [review]
The only additional change I might suggest is to bump neat to version 2.0.0.

**Comment by jrjohnson** [comment]
I haven't really looked into the 2.0 neat update.  Maybe release and tag this change with a major version bump and then do the neat update as another?

Or if you think its cool I can add that to this bump.  Your call.

**Comment by tzellman** [comment]
That makes the most sense. The api drastically changed in 2.0, so I doubt most users have upgraded.

**Comment by jrjohnson** [comment]
@tzellman turns out my question was too ambiguous.  Should I bump neat?

**Comment by tzellman** [comment]
I agree that it probably is the lowest risk to keep the same version of neat bundled in with this PR.

**Comment by jrjohnson** [comment]
Ok - great!  Then I think this is ready.

**Comment by jrjohnson** [comment]
@tsharman any thoughts on merging this?

**Comment by tsharman** [comment]
@jrjohnson sorry this took so long. Still trying to resolve why I'm not getting email notifications from Github.

**Comment by jrjohnson** [comment]
No problem. Thanks for the quick release after merging. I got the greenkeeper update notification before I saw that this had been merged.

**Pull request merged**
